import { Inbox } from "src/app/models/Inbox";

export const INBOXES: Inbox[] = [
  {
    folio: 1,
    detalle: "Detalle 1",
    cs: "cs 1",
    fechaCreacion: "fecha 1",
    movimiento: "movimiento 1",
    estatus: "estatus 1",
    referencia: "referencia 1",
    folioMedioAlt: "folioMedioAlt 1",
    fechaMedioAlt: "fechaMedioAlt 1",
    horaMedioAlt: "horaMedioAlt 1",
  },
  {
    folio: 2,
    detalle: "Detalle 2",
    cs: "cs 2",
    fechaCreacion: "fecha 2",
    movimiento: "movimiento 2",
    estatus: "estatus 2",
    referencia: "referencia 2",
    folioMedioAlt: "folioMedioAlt 2",
    fechaMedioAlt: "fechaMedioAlt 2",
    horaMedioAlt: "horaMedioAlt 2",
  },
  {
    folio: 3,
    detalle: "Detalle 3",
    cs: "cs 3",
    fechaCreacion: "fecha 3",
    movimiento: "movimiento 3",
    estatus: "estatus 3",
    referencia: "referencia 3",
    folioMedioAlt: "folioMedioAlt 3",
    fechaMedioAlt: "fechaMedioAlt 3",
    horaMedioAlt: "horaMedioAlt 3",
  },
  {
    folio: 4,
    detalle: "Detalle 4",
    cs: "cs 4",
    fechaCreacion: "fecha 4",
    movimiento: "movimiento 4",
    estatus: "estatus 4",
    referencia: "referencia 4",
    folioMedioAlt: "folioMedioAlt 4",
    fechaMedioAlt: "fechaMedioAlt 4",
    horaMedioAlt: "horaMedioAlt 4",
  },
  {
    folio: 5,
    detalle: "Detalle 5",
    cs: "cs 5",
    fechaCreacion: "fecha 5",
    movimiento: "movimiento 5",
    estatus: "estatus 5",
    referencia: "referencia 5",
    folioMedioAlt: "folioMedioAlt 5",
    fechaMedioAlt: "fechaMedioAlt 5",
    horaMedioAlt: "horaMedioAlt 5",
  },
  {
    folio: 6,
    detalle: "Detalle 6",
    cs: "cs 6",
    fechaCreacion: "fecha 6",
    movimiento: "movimiento 6",
    estatus: "estatus 6",
    referencia: "referencia 6",
    folioMedioAlt: "folioMedioAlt 6",
    fechaMedioAlt: "fechaMedioAlt 6",
    horaMedioAlt: "horaMedioAlt 6",
  },
  {
    folio: 7,
    detalle: "Detalle 7",
    cs: "cs 7",
    fechaCreacion: "fecha 7",
    movimiento: "movimiento 7",
    estatus: "estatus 7",
    referencia: "referencia 7",
    folioMedioAlt: "folioMedioAlt 7",
    fechaMedioAlt: "fechaMedioAlt 7",
    horaMedioAlt: "horaMedioAlt 7",
  },
  {
    folio: 8,
    detalle: "Detalle 8",
    cs: "cs 8",
    fechaCreacion: "fecha 8",
    movimiento: "movimiento 8",
    estatus: "estatus 8",
    referencia: "referencia 8",
    folioMedioAlt: "folioMedioAlt 8",
    fechaMedioAlt: "fechaMedioAlt 8",
    horaMedioAlt: "horaMedioAlt 8",
  },
  {
    folio: 10,
    detalle: "Detalle 10",
    cs: "cs 10",
    fechaCreacion: "fecha 10",
    movimiento: "movimiento 10",
    estatus: "estatus 10",
    referencia: "referencia 10",
    folioMedioAlt: "folioMedioAlt 10",
    fechaMedioAlt: "fechaMedioAlt 10",
    horaMedioAlt: "horaMedioAlt 10",
  },
  {
    folio: 11,
    detalle: "Detalle 11",
    cs: "cs 11",
    fechaCreacion: "fecha 11",
    movimiento: "movimiento 11",
    estatus: "estatus 11",
    referencia: "referencia 11",
    folioMedioAlt: "folioMedioAlt 11",
    fechaMedioAlt: "fechaMedioAlt 11",
    horaMedioAlt: "horaMedioAlt 11",
  },
  {
    folio: 12,
    detalle: "Detalle 12",
    cs: "cs 12",
    fechaCreacion: "fecha 12",
    movimiento: "movimiento 12",
    estatus: "estatus 12",
    referencia: "referencia 12",
    folioMedioAlt: "folioMedioAlt 12",
    fechaMedioAlt: "fechaMedioAlt 12",
    horaMedioAlt: "horaMedioAlt 12",
  },
  {
    folio: 13,
    detalle: "Detalle 13",
    cs: "cs 13",
    fechaCreacion: "fecha 13",
    movimiento: "movimiento 13",
    estatus: "estatus 13",
    referencia: "referencia 13",
    folioMedioAlt: "folioMedioAlt 13",
    fechaMedioAlt: "fechaMedioAlt 13",
    horaMedioAlt: "horaMedioAlt 13",
  },
  {
    folio: 14,
    detalle: "Detalle 14",
    cs: "cs 14",
    fechaCreacion: "fecha 14",
    movimiento: "movimiento 14",
    estatus: "estatus 14",
    referencia: "referencia 14",
    folioMedioAlt: "folioMedioAlt 14",
    fechaMedioAlt: "fechaMedioAlt 14",
    horaMedioAlt: "horaMedioAlt 14",
  },
  {
    folio: 15,
    detalle: "Detalle 15",
    cs: "cs 15",
    fechaCreacion: "fecha 15",
    movimiento: "movimiento 15",
    estatus: "estatus 15",
    referencia: "referencia 15",
    folioMedioAlt: "folioMedioAlt 15",
    fechaMedioAlt: "fechaMedioAlt 15",
    horaMedioAlt: "horaMedioAlt 15",
  },
  {
    folio: 16,
    detalle: "Detalle 16",
    cs: "cs 16",
    fechaCreacion: "fecha 16",
    movimiento: "movimiento 16",
    estatus: "estatus 16",
    referencia: "referencia 16",
    folioMedioAlt: "folioMedioAlt 16",
    fechaMedioAlt: "fechaMedioAlt 16",
    horaMedioAlt: "horaMedioAlt 16",
  },
  {
    folio: 17,
    detalle: "Detalle 17",
    cs: "cs 17",
    fechaCreacion: "fecha 17",
    movimiento: "movimiento 17",
    estatus: "estatus 17",
    referencia: "referencia 17",
    folioMedioAlt: "folioMedioAlt 17",
    fechaMedioAlt: "fechaMedioAlt 17",
    horaMedioAlt: "horaMedioAlt 17",
  },
  {
    folio: 18,
    detalle: "Detalle 18",
    cs: "cs 18",
    fechaCreacion: "fecha 18",
    movimiento: "movimiento 18",
    estatus: "estatus 18",
    referencia: "referencia 18",
    folioMedioAlt: "folioMedioAlt 18",
    fechaMedioAlt: "fechaMedioAlt 18",
    horaMedioAlt: "horaMedioAlt 18",
  },
  {
    folio: 19,
    detalle: "Detalle 19",
    cs: "cs 19",
    fechaCreacion: "fecha 19",
    movimiento: "movimiento 19",
    estatus: "estatus 19",
    referencia: "referencia 19",
    folioMedioAlt: "folioMedioAlt 19",
    fechaMedioAlt: "fechaMedioAlt 19",
    horaMedioAlt: "horaMedioAlt 19",
  },
  {
    folio: 20,
    detalle: "Detalle 20",
    cs: "cs 20",
    fechaCreacion: "fecha 20",
    movimiento: "movimiento 20",
    estatus: "estatus 20",
    referencia: "referencia 20",
    folioMedioAlt: "folioMedioAlt 20",
    fechaMedioAlt: "fechaMedioAlt 20",
    horaMedioAlt: "horaMedioAlt 20",
  },
];
export const INBOXES_BAJA: Inbox[] = [
  {
    folio: 11,
    detalle: "Detalle 11",
    cs: "cs 11",
    fechaCreacion: "fecha 11",
    movimiento: "movimiento 11",
    estatus: "estatus 11",
    referencia: "referencia 11",
    folioMedioAlt: "folioMedioAlt 11",
    fechaMedioAlt: "fechaMedioAlt 11",
    horaMedioAlt: "horaMedioAlt 11",
  },
  {
    folio: 12,
    detalle: "Detalle 12",
    cs: "cs 21",
    fechaCreacion: "fecha 12",
    movimiento: "movimiento 12",
    estatus: "estatus 12",
    referencia: "referencia 12",
    folioMedioAlt: "folioMedioAlt 12",
    fechaMedioAlt: "fechaMedioAlt 12",
    horaMedioAlt: "horaMedioAlt 12",
  },
  {
    folio: 13,
    detalle: "Detalle 13",
    cs: "cs 31",
    fechaCreacion: "fecha 13",
    movimiento: "movimiento 13",
    estatus: "estatus 13",
    referencia: "referencia 13",
    folioMedioAlt: "folioMedioAlt 13",
    fechaMedioAlt: "fechaMedioAlt 13",
    horaMedioAlt: "horaMedioAlt 13",
  },
  {
    folio: 14,
    detalle: "Detalle 14",
    cs: "cs 41",
    fechaCreacion: "fecha 14",
    movimiento: "movimiento 14",
    estatus: "estatus 14",
    referencia: "referencia 14",
    folioMedioAlt: "folioMedioAlt 14",
    fechaMedioAlt: "fechaMedioAlt 14",
    horaMedioAlt: "horaMedioAlt 14",
  },
  {
    folio: 15,
    detalle: "Detalle 15",
    cs: "cs 51",
    fechaCreacion: "fecha 15",
    movimiento: "movimiento 15",
    estatus: "estatus 15",
    referencia: "referencia 15",
    folioMedioAlt: "folioMedioAlt 15",
    fechaMedioAlt: "fechaMedioAlt 15",
    horaMedioAlt: "horaMedioAlt 15",
  },
  {
    folio: 16,
    detalle: "Detalle 16",
    cs: "cs 61",
    fechaCreacion: "fecha 16",
    movimiento: "movimiento 16",
    estatus: "estatus 16",
    referencia: "referencia 16",
    folioMedioAlt: "folioMedioAlt 16",
    fechaMedioAlt: "fechaMedioAlt 16",
    horaMedioAlt: "horaMedioAlt 16",
  },
  {
    folio: 17,
    detalle: "Detalle 17",
    cs: "cs 71",
    fechaCreacion: "fecha 17",
    movimiento: "movimiento 17",
    estatus: "estatus 17",
    referencia: "referencia 17",
    folioMedioAlt: "folioMedioAlt 17",
    fechaMedioAlt: "fechaMedioAlt 17",
    horaMedioAlt: "horaMedioAlt 17",
  },
  {
    folio: 18,
    detalle: "Detalle 18",
    cs: "cs 81",
    fechaCreacion: "fecha 18",
    movimiento: "movimiento 18",
    estatus: "estatus 18",
    referencia: "referencia 18",
    folioMedioAlt: "folioMedioAlt 18",
    fechaMedioAlt: "fechaMedioAlt 18",
    horaMedioAlt: "horaMedioAlt 18",
  },
  {
    folio: 110,
    detalle: "Detalle 110",
    cs: "cs 101",
    fechaCreacion: "fecha 110",
    movimiento: "movimiento 110",
    estatus: "estatus 110",
    referencia: "referencia 110",
    folioMedioAlt: "folioMedioAlt 110",
    fechaMedioAlt: "fechaMedioAlt 110",
    horaMedioAlt: "horaMedioAlt 110",
  },
  {
    folio: 111,
    detalle: "Detalle 111",
    cs: "cs 111",
    fechaCreacion: "fecha 111",
    movimiento: "movimiento 111",
    estatus: "estatus 111",
    referencia: "referencia 111",
    folioMedioAlt: "folioMedioAlt 111",
    fechaMedioAlt: "fechaMedioAlt 111",
    horaMedioAlt: "horaMedioAlt 111",
  },
  {
    folio: 112,
    detalle: "Detalle 112",
    cs: "cs 121",
    fechaCreacion: "fecha 112",
    movimiento: "movimiento 112",
    estatus: "estatus 112",
    referencia: "referencia 112",
    folioMedioAlt: "folioMedioAlt 112",
    fechaMedioAlt: "fechaMedioAlt 112",
    horaMedioAlt: "horaMedioAlt 112",
  },
  {
    folio: 113,
    detalle: "Detalle 113",
    cs: "cs 131",
    fechaCreacion: "fecha 113",
    movimiento: "movimiento 113",
    estatus: "estatus 113",
    referencia: "referencia 113",
    folioMedioAlt: "folioMedioAlt 113",
    fechaMedioAlt: "fechaMedioAlt 113",
    horaMedioAlt: "horaMedioAlt 113",
  },
  {
    folio: 114,
    detalle: "Detalle 114",
    cs: "cs 141",
    fechaCreacion: "fecha 114",
    movimiento: "movimiento 114",
    estatus: "estatus 114",
    referencia: "referencia 114",
    folioMedioAlt: "folioMedioAlt 114",
    fechaMedioAlt: "fechaMedioAlt 114",
    horaMedioAlt: "horaMedioAlt 114",
  },
  {
    folio: 115,
    detalle: "Detalle 115",
    cs: "cs 151",
    fechaCreacion: "fecha 115",
    movimiento: "movimiento 115",
    estatus: "estatus 115",
    referencia: "referencia 115",
    folioMedioAlt: "folioMedioAlt 115",
    fechaMedioAlt: "fechaMedioAlt 115",
    horaMedioAlt: "horaMedioAlt 115",
  },
  {
    folio: 116,
    detalle: "Detalle 116",
    cs: "cs 161",
    fechaCreacion: "fecha 116",
    movimiento: "movimiento 116",
    estatus: "estatus 116",
    referencia: "referencia 116",
    folioMedioAlt: "folioMedioAlt 116",
    fechaMedioAlt: "fechaMedioAlt 116",
    horaMedioAlt: "horaMedioAlt 116",
  },
  {
    folio: 117,
    detalle: "Detalle 117",
    cs: "cs 171",
    fechaCreacion: "fecha 117",
    movimiento: "movimiento 117",
    estatus: "estatus 117",
    referencia: "referencia 117",
    folioMedioAlt: "folioMedioAlt 117",
    fechaMedioAlt: "fechaMedioAlt 117",
    horaMedioAlt: "horaMedioAlt 117",
  },
  {
    folio: 118,
    detalle: "Detalle 118",
    cs: "cs 181",
    fechaCreacion: "fecha 118",
    movimiento: "movimiento 118",
    estatus: "estatus 118",
    referencia: "referencia 118",
    folioMedioAlt: "folioMedioAlt 118",
    fechaMedioAlt: "fechaMedioAlt 118",
    horaMedioAlt: "horaMedioAlt 118",
  },
  {
    folio: 119,
    detalle: "Detalle 119",
    cs: "cs 191",
    fechaCreacion: "fecha 119",
    movimiento: "movimiento 119",
    estatus: "estatus 119",
    referencia: "referencia 119",
    folioMedioAlt: "folioMedioAlt 119",
    fechaMedioAlt: "fechaMedioAlt 119",
    horaMedioAlt: "horaMedioAlt 119",
  },
  {
    folio: 120,
    detalle: "Detalle 120",
    cs: "cs 201",
    fechaCreacion: "fecha 210",
    movimiento: "movimiento 210",
    estatus: "estatus 210",
    referencia: "referencia 210",
    folioMedioAlt: "folioMedioAlt 210",
    fechaMedioAlt: "fechaMedioAlt 210",
    horaMedioAlt: "horaMedioAlt 210",
  },
];
